# Generated by Django 2.2.6 on 2019-10-12 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('beer', '0001_initial')
    ]

    def insertData(apps, schema_editor):
        BeerModel = apps.get_model('beer', 'BeerModel')
        beer1 = BeerModel(beer_type="LA", name="beer1", description="description1")
        beer2 = BeerModel(beer_type="AL", name="beer2", description="description2")
        beer3 = BeerModel(beer_type="ST", name="beer3", description="description3")

        beer1.save()
        beer2.save()
        beer3.save()

    operations = [
        migrations.RunPython(insertData),
    ]
