# Generated by Django 2.2.6 on 2019-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_type', models.CharField(choices=[('AL', 'Ale'), ('LA', 'Lager'), ('ST', 'Stout')], default='LA', max_length=2)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Beers',
            },
        ),
    ]
